### ISSUE TITLE
Missing a way to set an initial path

### ISSUE THREAD

**Issue by skrew** [filmicpro/SMBClient#1]
Hi,

First, congrats for the first lib smb/swift.

As i can see, your lib needs an initial SMBVolume then SMBPath.

Tell me if i'm wrong, but it's look like to be not possible to set an initial path (eg for favorite location) like:
`\\volume1\\path1\\path2\\`

All init's for SMBVolume / SMBPath are internal protected.

As we store favorites folders as String, it would be fine to have something like init(location: String), but as you need SMBVolume and SMBPath, i don't know how it can be handled.

Thanks

**Comment by sfaxon** [comment]
I've added `SMBPath(fromURL:)` as a failable initializer. 

I went back and forth for a while on supporting the windows style `\\server\volume\path`, but thought it would make more sense as a URL.
