### ISSUE TITLE
file.downloadPath ->  sourceFile.downloadPath

### ISSUE THREAD

**Issue by azureplus** [filmicpro/SMBClient#12]
let fopen = self.session.fileOpen(treeId: treeId, path: file.downloadPath, mod: UInt32(SMB_MOD_READ))

--->    

    let fopen = self.session.fileOpen(treeId: treeId, path: sourceFile.downloadPath, mod: UInt32(SMB_MOD_READ))

**Comment by brandonrains77** [comment]
what dos this do?
