### ISSUE TITLE
Direct Path

### ISSUE THREAD

**Issue by anonymouz4** [filmicpro/SMBClient#2]
Is there a way to set a path directly by a String?

And is it possible to manually connect for example only per IP address?

**Comment by sfaxon** [comment]
I just added `SMBPath(fromURL:)` which will take a URL with the format `smb://host/volume/path`

Regarding connecting to IP address, you should be able to get the NetBIOS name from:
`NetBIOSNameService#networkNameFor(ipAddress:)`
And give the result to:
`SMBServer(hostname: String, ipAddress: UInt32)`
